### ISSUE TITLE
undefined local variable or method `current_theme' for #<ActionView::Base:0x00000000042fb8>

### ISSUE THREAD

**Issue by captproton** [bullet-train-co/bullet_train-themes#9]
I upgraded,
to /ruby/3.1.2/lib/ruby/gems/3.1.0/gems/bullet_train-themes-1.0.15 (partial path),
and I got this:
![Action Controller Exception caught 2022-06-02 at 9 32 03 AM](https://user-images.githubusercontent.com/583/171679757-901f8af6-66ee-46cc-8c89-cd92f3df1ef4.jpg)

**Comment by captproton** [comment]
Just thought I would let you know.

**Comment by andrewculver** [comment]
@captproton Yup, something broke here. Going to enable CI on this repo and try to figure out where we went wrong.

**Comment by gazayas** [comment]
@captproton Are you still having this issue? Trying to reproduce here, can't seem to get the same error.
